### ISSUE TITLE
More info about the Vue related dependencies

### ISSUE THREAD

**Issue by delaneyj** [colinbate/svelte-ts-tailwind-template#1]
Just curious about these deps...

```
vue-eslint-parser
eslint-plugin-vue
```

Are they because `.svelte` files are very similar to `.vue`?

**Comment by colinbate** [comment]
That is a good question. I inherited those from the typescript template I used as the basis for this one. Your reasoning seems logical, but I may look into it to see if they can be removed now.

**Comment by colinbate** [comment]
I've updated the template to be a version of the official template with TypeScript pre-enabled and Tailwind added. I left out the ESLint and Prettier setup that the former one contained. That removed those dependencies. I'm not sure if ESLint still needs them for Svelte files or not.
