### ISSUE TITLE
Component styles not picked up

### ISSUE THREAD

**Issue by satb** [colinbate/svelte-ts-tailwind-template#2]
If we have a style defined on the component, for example, in Counter.svelte, the styles don't take effect nor are included in the bundle.css file but it is there in the bundle.css.map. Thoughts on how to fix this?

```
<script lang="ts">
  export let value = 0;
  export let step = 1;
</script>

<style>
  .counterStyle {
    background-color: red;
  }
</style>

<div class="counterStyle">
  <slot>Default Counter</slot>
  <div class="rounded bg-black text-green-300 mb-2 inline-flex">
    <span class="py-1 px-3 w-16 text-center">{value}</span>
    <button class="text-black bg-gray-400 py-1 px-3" on:click={() => (value += step)}>+</button>
    <button class="text-black bg-gray-400 py-1 px-3 ml-px rounded rounded-l-none" on:click={() => (value -= step)}>-</button>
  </div>
</div>
```

**Comment by affandhia** [comment]
I got the same issue @satb . 

It turns out that you need to separate the css file by `postcss` plugin from the css file by `svelte` plugin.

https://github.com/colinbate/svelte-ts-tailwind-template/blob/47e8f531cbec15b67db76b0bcf630bcce8b0fff3/rollup.config.js#L19

that line is supposed to be changed into like this:
```
 postcss({ extract: "<css name here>.css" }), 
```

then you need to import the the <css name here>.css into your public/index.html
```
<link rel='stylesheet' href='bundle.css'>
<link rel='stylesheet' href='<css name here>.css'>
```

**Comment by colinbate** [comment]
Thanks for the note, and I agree, this template is certainly not one you want to use anymore. It was based on two other templates, neither of which are the best options now (or even when I created this template probably).

TypeScript is now supported via a somewhat official option, and Tailwind/PostCSS also has a better setup. I have another repo which has Tailwind that you could use: https://github.com/colinbate/svelte-tailwindcss-template. Perhaps I will update this one with the latest combination of the two, as I suspect I will use it myself now there is a proper TS option.

**Comment by colinbate** [comment]
I've updated this template to use the latest official TS setup and the latest Tailwind version/setup. Any custom styles should be included in bundle.css now.
