### ISSUE TITLE
Tailwind unused CSS is not cleaned on bundle.css after npm run build

### ISSUE THREAD

**Issue by bbohec** [colinbate/svelte-ts-tailwind-template#3]
Hi @colinbate ,

I would expect that any npm run build will ask rollup/postcss/tailwind/... to remove unused CSS on `bundle.css`
Actually by using small amount of tailwind CSS on svelte, the CSS bundle size is approx 4.7MB.
That's ok for `npm run dev`, but for `npm run build` this may be optimized even if build time is increased.

Does reduced CSS bundle is only applied on production environment?

Regards,
Ben.

**Comment by colinbate** [comment]
Ah yea, it requires that `NODE_ENV` is set to `production`. My CI has that set up but it is worth mentioning. I’ll add a note. I’d rather not add `cross-env` as a dependency but I’ll give it some thought tonight.

**Comment by colinbate** [comment]
This should be fixed with the JIT set up for Tailwind.
